/home/marksa/dev/PyCharm/Gnucash/venv/bin/python /home/marksa/apps/pycharm-community-2018.3/helpers/pydev/pydevconsole.py --mode=client --port=38789

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/marksa/dev/PyCharm/Gnucash/AcctAnalysis'])

PyDev console: starting.

Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
>>> runfile('/home/marksa/dev/PyCharm/Gnucash/CreateTxs/makeGncTx/createGnucashTxs.py', args=['jsonFromTxt/Monarch-Lulu_txRep_2019-1.2019-02-08_06-04-15.json', '/home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc', 'PROD'], wdir='/home/marksa/dev/PyCharm/Gnucash/CreateTxs/makeGncTx')

gncFile = '/home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc'


Plan type = 'OPEN'
rev_path = '['REV', 'REV_Invest', 'Dist', 'OPEN']'
rev_acct = 'OPEN'
ast_parent_path = '['FAMILY', 'INVEST', 'OPEN']'
ast_parent = 'OPEN'
ast_acct_name = 'CIG 11461'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'CIG 11461'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'CIG 11461' 
(u'', u'35', u'11')
gross_curr = '3511'
gross_opp = '-3511'
(u'', u'3', u'8910')
units = '38910'
('01', '25', '2019')
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'CI Investments: Reinvested:Distribution/Interest: CIG 11461'
notes = 'CIG 11461 balance = 706.1040'
gtx guid = '500573d4d7d3e6578484177b79139ddd'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

ast_acct_name = 'CIG 11111'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'CIG 11111'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'CIG 11111' 
(u'', u'5', u'39')
gross_curr = '539'
gross_opp = '-539'
(u'', u'0', u'5970')
units = '5970'
('01', '25', '2019')
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'CI Investments: Reinvested:Distribution/Interest: CIG 11111'
notes = 'CIG 11111 balance = 108.4690'
gtx guid = 'f653ca29b4dbf162fee635d4de9f5565'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

ast_acct_name = 'CIG 18140'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'CIG 18140'
type(ast_acct_str) = '<type 'str'>'

 ast_parent = 'TRUST'

 rev_acct = 'Trust Base'
[createGnucashTxs.py@144]: 
 ast_acct = 'CIG 18140' 
(u'(', u'1,000', u'00')
gross_curr = '-100000'
gross_opp = '100000'
(u'-', u'67', u'2970')
units = '-672970'
('01', '11', '2019')
trade_mth = '1'
trade_day = '11'
trade_yr = '2019'
descr = 'CI Investments: Automatic/Systematic:Withdrawal Plan:(AWD/SWP): CIG 18140'
notes = 'CIG 18140 balance = 6332.2800'
gtx guid = '6643b4c4cb0418ce34ce234025a301b2'
gtx date = '1547204340'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 


Plan type = 'TFSA'
rev_path = '['REV', 'REV_Invest', 'Dist', 'TFSA', 'Lulu']'
rev_acct = 'Lulu'
ast_parent_path = '['FAMILY', 'INVEST', 'TFSA', 'Lulu']'
ast_parent = 'Lulu'
ast_acct_name = 'MFC 3689'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 3689'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 3689' 
(u'(', u'979', u'54')
gross_curr = '-97954'
gross_opp = '97954'
(u'-', u'82', u'9670')
units = '-829670'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-Out: MFC 3689'
notes = 'MFC 3689 balance = 740.8990'
transfer

ast_acct_name = 'MFC 3689'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 3689'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 3689' 
(u'', u'36', u'67')
gross_curr = '3667'
gross_opp = '-3667'
(u'', u'3', u'0030')
units = '30030'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 3689'
notes = 'MFC 3689 balance = 743.9020'
gtx guid = '5c36a4ff78fab216937064dfbfd97929'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 1960'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 1960'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 1960' 
(u'', u'979', u'54')
gross_curr = '97954'
gross_opp = '-97954'
(u'', u'82', u'9670')
units = '829670'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-In: MFC 1960'
notes = 'MFC 1960 balance = 985.3310'
transfer
gtx guid = '092301dc723b058ad12752d06e720857'
gtx date = '1546513140'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 1960'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 1960'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 1960' 
(u'', u'48', u'77')
gross_curr = '4877'
gross_opp = '-4877'
(u'', u'3', u'9940')
units = '39940'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 1960'
notes = 'MFC 1960 balance = 989.3250'
gtx guid = 'ab4fc71bb78e4d9c6bd362590efb7f28'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 3232'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 3232'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 3232' 
(u'(', u'973', u'53')
gross_curr = '-97353'
gross_opp = '97353'
(u'-', u'119', u'2030')
units = '-1192030'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-Out: MFC 3232'
notes = 'MFC 3232 balance = 1064.4940'
transfer

ast_acct_name = 'MFC 3232'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 3232'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 3232' 
(u'', u'36', u'51')
gross_curr = '3651'
gross_opp = '-3651'
(u'', u'4', u'3220')
units = '43220'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 3232'
notes = 'MFC 3232 balance = 1068.8160'
gtx guid = 'f1870db33ea14b2ffd7657b93a4ff2e5'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 6138'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6138'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6138' 
(u'', u'973', u'53')
gross_curr = '97353'
gross_opp = '-97353'
(u'', u'73', u'7610')
units = '737610'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-In: MFC 6138'
notes = 'MFC 6138 balance = 1773.8520'
transfer
gtx guid = '9ce4564d174a679ba9006de6299d5c30'
gtx date = '1546513140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 6138'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6138'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6138' 
(u'', u'98', u'27')
gross_curr = '9827'
gross_opp = '-9827'
(u'', u'7', u'1980')
units = '71980'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 6138'
notes = 'MFC 6138 balance = 1781.0500'
gtx guid = 'ca1bdb92c5706a05e780a96b92397d3d'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 


Plan type = 'RRSP'
rev_path = '['REV', 'REV_Invest', 'Dist', 'RRSP', 'Lulu']'
rev_acct = 'Lulu'
ast_parent_path = '['FAMILY', 'INVEST', 'RRSP', 'Lulu']'
ast_parent = 'Lulu'
ast_acct_name = 'MFC 6130'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6130'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6130' 
(u'', u'668', u'28')
gross_curr = '66828'
gross_opp = '-66828'
(u'', u'74', u'8500')
units = '748500'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-In: MFC 6130'
notes = 'MFC 6130 balance = 816.8210'
transfer

ast_acct_name = 'MFC 6130'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6130'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6130' 
(u'', u'25', u'08')
gross_curr = '2508'
gross_opp = '-2508'
(u'', u'2', u'7570')
units = '27570'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 6130'
notes = 'MFC 6130 balance = 819.5780'
gtx guid = 'b4d77ca89cd7d39a2ad5ef996b81ebcf'
gtx date = '1547809140'
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 3232'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 3232'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 3232' 
(u'(', u'1,560', u'20')
gross_curr = '-156020'
gross_opp = '156020'
(u'-', u'191', u'0370')
units = '-1910370'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-Out: MFC 3232'
notes = 'MFC 3232 balance = 1705.9800'
transfer

ast_acct_name = 'MFC 3232'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 3232'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 3232' 
(u'', u'58', u'52')
gross_curr = '5852'
gross_opp = '-5852'
(u'', u'6', u'9270')
units = '69270'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 3232'
notes = 'MFC 3232 balance = 1712.9070'
gtx guid = 'c871cf5590c9f0ba9d1473507f42596b'
gtx date = '1547809140'
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 6138'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6138'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6138' 
(u'', u'1,560', u'20')
gross_curr = '156020'
gross_opp = '-156020'
(u'', u'118', u'2110')
units = '1182110'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-In: MFC 6138'
notes = 'MFC 6138 balance = 1305.5650'
transfer
gtx guid = '64c82bde883682acfabe49f3312fe328'
gtx date = '1546513140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 6138'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6138'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6138' 
(u'', u'72', u'33')
gross_curr = '7233'
gross_opp = '-7233'
(u'', u'5', u'2970')
units = '52970'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 6138'
notes = 'MFC 6138 balance = 1310.8620'
gtx guid = '88a9e52300a9725997a872f86bb44523'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 302'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 302'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 302' 
(u'(', u'963', u'46')
gross_curr = '-96346'
gross_opp = '96346'
(u'-', u'70', u'6110')
units = '-706110'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-Out: MFC 302'
notes = 'MFC 302 balance = 641.3550'
transfer

ast_acct_name = 'MFC 302'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 302'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 302' 
(u'', u'8', u'79')
gross_curr = '879'
gross_opp = '-879'
(u'', u'0', u'6500')
units = '6500'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 302'
notes = 'MFC 302 balance = 642.0050'
gtx guid = 'a60ae4b45fe1a4a340399d8d3ac64896'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 6129'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6129'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6129' 
(u'', u'963', u'46')
gross_curr = '96346'
gross_opp = '-96346'
(u'', u'93', u'4350')
units = '934350'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-In: MFC 6129'
notes = 'MFC 6129 balance = 993.5440'
transfer
gtx guid = '691d2e2ec74aefaf0b1c10993fd0b88f'
gtx date = '1546513140'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 6129'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 6129'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 6129' 
(u'', u'13', u'61')
gross_curr = '1361'
gross_opp = '-1361'
(u'', u'1', u'3320')
units = '13320'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 6129'
notes = 'MFC 6129 balance = 994.8760'
gtx guid = 'e43230afaef67250557f5c245818cb43'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 856'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 856'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 856' 
(u'(', u'668', u'28')
gross_curr = '-66828'
gross_opp = '66828'
(u'-', u'162', u'1650')
units = '-1621650'
('01', '03', '2019')
trade_mth = '1'
trade_day = '3'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Switch-Out: MFC 856'
notes = 'MFC 856 balance = 1459.1670'
transfer
gtx guid = '5df8a91aa553c871e4c1c89e8c7b7eba'
gtx date = '1546513140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MFC 856'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MFC 856'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MFC 856' 
(u'', u'18', u'97')
gross_curr = '1897'
gross_opp = '-1897'
(u'', u'4', u'5180')
units = '45180'
('01', '18', '2019')
trade_mth = '1'
trade_day = '18'
trade_yr = '2019'
descr = 'Mackenzie Financial Corp: Reinvested:Distribution/Interest: MFC 856'
notes = 'MFC 856 balance = 1463.6850'
gtx guid = '66f429f562b6c67dcf07f5fda12ed5d9'
gtx date = '1547809140'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'DYN 029'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 029'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 029' 
(u'', u'5,415', u'29')
gross_curr = '541529'
gross_opp = '-541529'
(u'', u'269', u'6858')
units = '2696858'
('01', '15', '2019')
trade_mth = '1'
trade_day = '15'
trade_yr = '2019'
descr = 'Dynamic Funds: Switch-In: DYN 029'
notes = 'DYN 029 balance = 707.1301'
transfer

ast_acct_name = 'DYN 029'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 029'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 029' 
(u'', u'49', u'50')
gross_curr = '4950'
gross_opp = '-4950'
(u'', u'2', u'4372')
units = '24372'
('01', '25', '2019')
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'Dynamic Funds: Reinvested:Distribution/Interest: DYN 029'
notes = 'DYN 029 balance = 709.5673'
gtx guid = '1ab0d4327d855b854c5b2dde0580c51f'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'DYN 1562'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 1562'
type(ast_acct_str) = '<type 'str'>'
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 1562' 
(u'(', u'4,754', u'37')
gross_curr = '-475437'
gross_opp = '475437'
(u'-', u'360', u'1796')
units = '-3601796'
('01', '15', '2019')
trade_mth = '1'
trade_day = '15'
trade_yr = '2019'
descr = 'Dynamic Funds: Switch-Out: DYN 1562'
notes = 'DYN 1562 balance = 132.1599'
transfer

ast_acct_name = 'DYN 1562'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 1562'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 1562' 
(u'', u'7', u'72')
gross_curr = '772'
gross_opp = '-772'
(u'', u'0', u'5835')
units = '5835'
('01', '25', '2019')
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'Dynamic Funds: Reinvested:Distribution/Interest: DYN 1562'
notes = 'DYN 1562 balance = 132.7434'
gtx guid = '4e5bc4c08027be62d8494c1e1851dfd0'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'DYN 729'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 729'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 729' 
(u'(', u'5,415', u'29')
gross_curr = '-541529'
gross_opp = '541529'
(u'-', u'269', u'6858')
units = '-2696858'
('01', '15', '2019')
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
trade_mth = '1'
trade_day = '15'
trade_yr = '2019'
descr = 'Dynamic Funds: Switch-Out: DYN 729'
notes = 'DYN 729 balance = 107.2700'
transfer
gtx guid = 'b919d6bddc945076b9dcbf72f1e8427d'
gtx date = '1547549940'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'DYN 729'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 729'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 729' 
(u'', u'7', u'51')
gross_curr = '751'
gross_opp = '-751'
(u'', u'0', u'3698')
units = '3698'
('01', '25', '2019')
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'Dynamic Funds: Reinvested:Distribution/Interest: DYN 729'
notes = 'DYN 729 balance = 107.6398'
gtx guid = '65f7e7838d51304cd2f1edabc43a50a3'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'TML 1018'
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'TML 1018'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'TML 1018' 
(u'(', u'4,497', u'90')
gross_curr = '-449790'
gross_opp = '449790'
(u'-', u'331', u'9407')
units = '-3319407'
('01', '15', '2019')
trade_mth = '1'
trade_day = '15'
trade_yr = '2019'
descr = 'Franklin Templeton: Switch-Out: TML 1018'
notes = 'TML 1018 balance = 69.1905'
transfer

ast_acct_name = 'TML 1018'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'TML 1018'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'TML 1018' 
(u'', u'2', u'25')
gross_curr = '225'
gross_opp = '-225'
(u'', u'0', u'1628')
units = '1628'
('01', '30', '2019')
trade_mth = '1'
trade_day = '30'
trade_yr = '2019'
descr = 'Franklin Templeton: Reinvested:Distribution/Interest: TML 1018'
notes = 'TML 1018 balance = 69.3533'
gtx guid = '7cfc2506edf9001e7b47eaf151d4af11'
gtx date = '1548845940'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'TML 1017'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'TML 1017'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'TML 1017' 
(u'', u'4,497', u'90')
gross_curr = '449790'
gross_opp = '-449790'
(u'', u'331', u'9407')
units = '3319407'
('01', '15', '2019')
trade_mth = '1'
trade_day = '15'
trade_yr = '2019'
descr = 'Franklin Templeton: Switch-In: TML 1017'
notes = 'TML 1017 balance = 423.8556'
transfer
gtx guid = '56693b469f287aee8147dadc0319c120'
gtx date = '1547549940'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'TML 1017'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'TML 1017'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'TML 1017' 
(u'', u'13', u'78')
gross_curr = '1378'
gross_opp = '-1378'
(u'', u'0', u'9971')
units = '9971'
('01', '30', '2019')
trade_mth = '1'
trade_day = '30'
trade_yr = '2019'
descr = 'Franklin Templeton: Reinvested:Distribution/Interest: TML 1017'
notes = 'TML 1017 balance = 424.8527'
gtx guid = '9fd3b2a4702e3b2d61f5d9fc5314bb7e'
gtx date = '1548845940'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'DYN 1560'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 1560'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 1560' 
(u'', u'4,754', u'37')
gross_curr = '475437'
gross_opp = '-475437'
(u'', u'360', u'1796')
units = '3601796'
('01', '15', '2019')
trade_mth = '1'
trade_day = '15'
trade_yr = '2019'
descr = 'Dynamic Funds: Switch-In: DYN 1560'
notes = 'DYN 1560 balance = 937.7491'
transfer
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
gtx guid = '39e2fda0c7013fce96ec250d171fa12b'
gtx date = '1547549940'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'DYN 1560'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'DYN 1560'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'DYN 1560' 
(u'', u'54', u'76')
gross_curr = '5476'
gross_opp = '-5476'
(u'', u'4', u'1391')
units = '41391'
('01', '25', '2019')
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'Dynamic Funds: Reinvested:Distribution/Interest: DYN 1560'
notes = 'DYN 1560 balance = 941.8882'
gtx guid = '3a189a515f16797a0b9cbde30ba6d1b0'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MMF 4524'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MMF 4524'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MMF 4524' 
(u'', u'2,312', u'10')
gross_curr = '231210'
gross_opp = '-231210'
(u'', u'255', u'1140')
units = '2551140'
('01', '22', '2019')
trade_mth = '1'
trade_day = '22'
trade_yr = '2019'
descr = 'Manulife Mutual Funds: Switch-In: MMF 4524'
notes = 'MMF 4524 balance = 2856.5600'
transfer

ast_acct_name = 'MMF 4524'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MMF 4524'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MMF 4524' 
(u'', u'142', u'83')
gross_curr = '14283'
gross_opp = '-14283'
(u'', u'15', u'7930')
units = '157930'
('01', '25', '2019')
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'Manulife Mutual Funds: Reinvested:Distribution/Interest: MMF 4524'
notes = 'MMF 4524 balance = 2872.3530'
gtx guid = '7e04323aa7aa2f1a6223178d7dbae855'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MMF 44424'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MMF 44424'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MMF 44424' 
(u'(', u'2,312', u'10')
gross_curr = '-231210'
gross_opp = '231210'
(u'-', u'255', u'1140')
units = '-2551140'
('01', '22', '2019')
trade_mth = '1'
trade_day = '22'
trade_yr = '2019'
descr = 'Manulife Mutual Funds: Switch-Out: MMF 44424'
notes = 'MMF 44424 balance = 106.7310'
transfer
gtx guid = '3f4cec221e218181660b1591db31d7a6'
gtx date = '1548154740'
Mode = 'PROD': Commit transaction changes.

* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
ast_acct_name = 'MMF 44424'
type(ast_acct_name) = '<type 'unicode'>'
ast_acct_str = 'MMF 44424'
type(ast_acct_str) = '<type 'str'>'
[createGnucashTxs.py@144]: 
 ast_acct = 'MMF 44424' 
(u'', u'5', u'34')
gross_curr = '534'
gross_opp = '-534'
(u'', u'0', u'5900')
units = '5900'
('01', '25', '2019')
trade_mth = '1'
trade_day = '25'
trade_yr = '2019'
descr = 'Manulife Mutual Funds: Reinvested:Distribution/Interest: MMF 44424'
notes = 'MMF 44424 balance = 107.3210'
gtx guid = 'a90d04d869fccdba83e1f919e78f2199'
gtx date = '1548413940'
Mode = 'PROD': Commit transaction changes.

[createGnucashTxs.py@285]: create_gnc_tx() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR'
 
[createGnucashTxs.py@315]: Mode = 'PROD': Save session. 
* 07:25:00  WARN <gnc.backend> [gnc_int_link_or_make_backup()] unable to make file backup from /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc to /home/marksa/dev/git/Python/Gnucash/gncFiles/test4.gnc.20190209072500.gnucash: File exists
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/marksa/apps/pycharm-community-2018.3/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/marksa/dev/PyCharm/Gnucash/CreateTxs/makeGncTx/createGnucashTxs.py", line 384, in <module>
    create_gnc_txs_main()
  File "/home/marksa/dev/PyCharm/Gnucash/CreateTxs/makeGncTx/createGnucashTxs.py", line 378, in create_gnc_txs_main
    create_gnc_txs(tx_collxn, gnc_file, mode)
  File "/home/marksa/dev/PyCharm/Gnucash/CreateTxs/makeGncTx/createGnucashTxs.py", line 316, in create_gnc_txs
    session.save()
  File "/home/marksa/.local/lib/python2.7/site-packages/gnucash/gnucash_core.py", line 150, in new_function
    self.raise_backend_errors(function.__name__)
  File "/home/marksa/.local/lib/python2.7/site-packages/gnucash/gnucash_core.py", line 128, in raise_backend_errors
    errors )
GnuCashBackendException: call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR
[createGnucashTxs.py@344]: create_gnc_txs() EXCEPTION!! 'call to new_function resulted in the following errors, ERR_FILEIO_BACKUP_ERROR' 
